name: Deploy to AWS S3 and GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Configure AWS CLI
        run: |
          # Configure AWS CLI
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Replace with your desired region
          aws configure set default.output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify AWS CLI Version
        run: aws --version

      - name: Install dependencies
        run: npm install

      - name: Build the React app for AWS S3
        run: |
          REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} REACT_APP_CONTACT_FORM_API=${{ secrets.REACT_APP_CONTACT_FORM_API }} REACT_APP_SEND_EMAIL_API=${{ secrets.REACT_APP_SEND_EMAIL_API }} REACT_APP_CHECK_EMAIL=${{ secrets.REACT_APP_CHECK_EMAIL }} npm run build

      - name: Deploy to AWS S3
        run: |
          if [ $GITHUB_REF = 'refs/heads/main' ]; then
            aws s3 sync ./build s3://esceniarte.com
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to GitHub Pages
        run: |
          # Cleanup previous build
          rm -rf build
          # Build the app for GitHub Pages
          REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} REACT_APP_CONTACT_FORM_API=${{ secrets.REACT_APP_CONTACT_FORM_API }} REACT_APP_SEND_EMAIL_API=${{ secrets.REACT_APP_SEND_EMAIL_API }} REACT_APP_CHECK_EMAIL=${{ secrets.REACT_APP_CHECK_EMAIL }} npm run build
          # Setup Git identity
          git config user.email "sara_moreira@hotmail.es"
          git config user.name "SaraMoreiraG"
          # Deploy to GitHub Pages
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
          git checkout main
          git branch -D gh-pages
        env:
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_CONTACT_FORM_API: ${{ secrets.REACT_APP_CONTACT_FORM_API }}
          REACT_APP_SEND_EMAIL_API: ${{ secrets.REACT_APP_SEND_EMAIL_API }}
          REACT_APP_CHECK_EMAIL: ${{ secrets.REACT_APP_CHECK_EMAIL }}
